version: '3'
services:
    wordpress:
        image: wordpress:latest
        container_name: wordpress-wordpress-1
        ports:
            - "5080:80"
        volumes:
            - ./wp-content:/var/www/html/wp-content
        depends_on:
            - mysql
        environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: "password"
          WORDPRESS_DB_NAME: wordpress
        networks:
          thenet:
            ipv4_address: 10.53.1.2
    mysql:
       image: "mysql:5.7"
       environment:
         MYSQL_DATABASE: wordpress
         MYSQL_ROOT_PASSWORD: "password"
       volumes:
         - ./mysql:/var/lib/mysql
       networks:
         thenet:
           ipv4_address: 10.53.1.3
networks:
   thenet:
     ipam:
       driver: default
       config:
         - subnet: "10.53.1.0/24"
